[tool.poetry]
name = "transformer"
version = "0.1.0"
description = ""
authors = ["arnekugel <arne-malte.kugel@gmx.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
